import { Discount } from "@/types/product";

export const dummyDiscounts: Discount[] = [
  {
    id: "1",
    couponCode: "WELCOME10",
    type: "coupon",
    value: 10,
    description: "Flat 10 EGP off on your first order",
    startDate: "2025-10-01",
    endDate: "2025-10-31",
    status: "active", // 👈 depends on your DiscountStatus enum
    store: "fashion", // 👈 depends on your StoreType
    canUseWithPromotion: false,
    discountType: "fixed",
    applyFor: "all_orders",
    canUseWithFlashSale: false,
    isUnlimited: true,
    applyViaUrl: false,
    displayAtCheckout: true,
    neverExpired: false,
  },
  {
    id: "2",
    couponCode: "FREESHIP15",
    type: "coupon",
    value: 15,
    description: "Free shipping up to 15 EGP",
    startDate: "2025-10-01",
    endDate: "2025-12-31",
    status: "active",
    store: "default",
    canUseWithPromotion: true,
    discountType: "shipping",
    applyFor: "all_orders",
    canUseWithFlashSale: true,
    isUnlimited: false,
    applyViaUrl: true,
    displayAtCheckout: false,
    neverExpired: true,
  },
  {
    id: "3",
    couponCode: "SAVE30",
    type: "promotion",
    value: 30,
    description: "30% off on selected products",
    startDate: "2025-10-05",
    endDate: "2025-11-05",
    status: "scheduled",
    store: "electronics",
    canUseWithPromotion: false,
    discountType: "percentage",
    applyFor: "specific_products",
    canUseWithFlashSale: false,
    isUnlimited: false,
    applyViaUrl: true,
    displayAtCheckout: true,
    neverExpired: false,
  },
  {
    id: "4",
    couponCode: "BIGSALE2025",
    type: "promotion",
    value: 50,
    description: "50% off sitewide for limited time",
    startDate: "2025-11-01",
    endDate: "2025-11-10",
    status: "active",
    store: "fashion",
    canUseWithPromotion: true,
    discountType: "percentage",
    applyFor: "all_orders",
    canUseWithFlashSale: true,
    isUnlimited: false,
    applyViaUrl: false,
    displayAtCheckout: true,
    neverExpired: false,
  },
];
