import { PageType } from "@/types";

// ✅ Dummy unified multilingual pages data
export const dummyPages: PageType[] = [
  {
    id: "1",
    name: { en: "Home Page", ar: "الصفحة الرئيسية" },
    description: {
      en: "Welcome to our home page with the latest updates",
      ar: "مرحبًا بك في صفحتنا الرئيسية مع أحدث التحديثات",
    },
    content: {
      en: '[home-slider images="main/slider1.jpg,main/slider2.jpg" title="Welcome to Our Site"]',
      ar: '[home-slider images="main/slider1.jpg,main/slider2.jpg" title="مرحبًا بكم في موقعنا"]',
    },
    template: "home",
    breadcrumb_style: "start",
    breadcrumb_background: "",
    status: "published",
    featured_image: "main/slider1.jpg",
    faqs: [],
    seo: {
      meta_title: { en: "Home Page", ar: "الصفحة الرئيسية" },
      meta_description: {
        en: "Explore our website homepage and discover new updates.",
        ar: "استكشف صفحتنا الرئيسية واكتشف أحدث التحديثات.",
      },
      meta_image: "main/slider1.jpg",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-01-15T10:30:00Z",
    lastModified: "2024-03-20T14:25:00Z",
    author: "Admin User",
  },
  {
    id: "2",
    name: { en: "About Us", ar: "من نحن" },
    description: {
      en: "Learn more about our company and mission.",
      ar: "تعرّف على المزيد حول شركتنا ورسالتنا.",
    },
    content: {
      en: '[about-section title="Who We Are" image="main/general/about.jpg"]',
      ar: '[about-section title="من نحن" image="main/general/about.jpg"]',
    },
    template: "about",
    breadcrumb_style: "center",
    breadcrumb_background: "",
    status: "published",
    featured_image: "main/general/about.jpg",
    faqs: [],
    seo: {
      meta_title: { en: "About Us", ar: "من نحن" },
      meta_description: {
        en: "Information about our company, mission, and team.",
        ar: "معلومات عن شركتنا ورسالتنا وفريقنا.",
      },
      meta_image: "main/general/about.jpg",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-01-20T09:15:00Z",
    lastModified: "2024-02-28T11:45:00Z",
    author: "Admin User",
  },
  {
    id: "3",
    name: { en: "Contact Information", ar: "معلومات الاتصال" },
    description: {
      en: "Get in touch with us through the contact form.",
      ar: "تواصل معنا من خلال نموذج الاتصال.",
    },
    content: {
      en: '[contact-form title="Get In Touch" address="123 Main St" email="info@example.com"]',
      ar: '[contact-form title="تواصل معنا" address="123 الشارع الرئيسي" email="info@example.com"]',
    },
    template: "contact",
    breadcrumb_style: "center",
    breadcrumb_background: "",
    status: "published",
    featured_image: "main/general/contact.jpg",
    faqs: [],
    seo: {
      meta_title: { en: "Contact Us", ar: "اتصل بنا" },
      meta_description: {
        en: "Contact information and inquiry form.",
        ar: "معلومات الاتصال ونموذج الاستفسار.",
      },
      meta_image: "main/general/contact.jpg",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-02-01T16:20:00Z",
    lastModified: "2024-03-15T13:30:00Z",
    author: "Content Manager",
  },
  {
    id: "4",
    name: { en: "Our Services", ar: "خدماتنا" },
    description: {
      en: "Discover the wide range of services we provide.",
      ar: "اكتشف مجموعة الخدمات التي نقدمها.",
    },
    content: {
      en: '[services-list title="Our Services" layout="grid" count="6"]',
      ar: '[services-list title="خدماتنا" layout="grid" count="6"]',
    },
    template: "services",
    breadcrumb_style: "center",
    breadcrumb_background: "",
    status: "draft",
    featured_image: "main/general/services.jpg",
    faqs: [],
    seo: {
      meta_title: { en: "Our Services", ar: "خدماتنا" },
      meta_description: {
        en: "View our professional services and solutions.",
        ar: "تعرّف على خدماتنا المهنية وحلولنا.",
      },
      meta_image: "main/general/services.jpg",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-02-10T14:00:00Z",
    lastModified: "2024-03-18T10:15:00Z",
    author: "Service Manager",
  },
  {
    id: "5",
    name: { en: "Company Blog", ar: "مدونة الشركة" },
    description: {
      en: "Read our latest news and articles.",
      ar: "اقرأ آخر الأخبار والمقالات الخاصة بنا.",
    },
    content: {
      en: '[blog-list layout="grid" count="5"]',
      ar: '[blog-list layout="grid" count="5"]',
    },
    template: "blog",
    breadcrumb_style: "center",
    breadcrumb_background: "",
    status: "published",
    featured_image: "main/general/blog.jpg",
    faqs: [],
    seo: {
      meta_title: { en: "Company Blog", ar: "مدونة الشركة" },
      meta_description: {
        en: "Stay updated with our latest news and posts.",
        ar: "ابقَ على اطلاع بأحدث الأخبار والمنشورات.",
      },
      meta_image: "main/general/blog.jpg",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-02-15T11:45:00Z",
    lastModified: "2024-03-22T08:30:00Z",
    author: "Content Manager",
  },
  {
    id: "6",
    name: { en: "Privacy Policy", ar: "سياسة الخصوصية" },
    description: {
      en: "Our policies regarding user data and privacy.",
      ar: "سياساتنا المتعلقة ببيانات المستخدم والخصوصية.",
    },
    content: { en: "[privacy-policy]", ar: "[privacy-policy]" },
    template: "custom",
    breadcrumb_style: "start",
    breadcrumb_background: "",
    status: "published",
    featured_image: "",
    faqs: [],
    seo: {
      meta_title: { en: "Privacy Policy", ar: "سياسة الخصوصية" },
      meta_description: {
        en: "Read our privacy policy and user data protection rules.",
        ar: "اقرأ سياسة الخصوصية الخاصة بنا وقواعد حماية بيانات المستخدم.",
      },
      meta_image: "",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-03-01T12:00:00Z",
    lastModified: "2024-03-01T12:00:00Z",
    author: "Admin User",
  },
  {
    id: "7",
    name: { en: "Terms of Service", ar: "شروط الخدمة" },
    description: {
      en: "The terms and conditions for using our services.",
      ar: "الشروط والأحكام لاستخدام خدماتنا.",
    },
    content: { en: "[terms-of-service]", ar: "[terms-of-service]" },
    template: "custom",
    breadcrumb_style: "start",
    breadcrumb_background: "",
    status: "draft",
    featured_image: "",
    faqs: [],
    seo: {
      meta_title: { en: "Terms of Service", ar: "شروط الخدمة" },
      meta_description: {
        en: "Terms and conditions of using our services.",
        ar: "الشروط والأحكام الخاصة باستخدام خدماتنا.",
      },
      meta_image: "",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-03-05T15:30:00Z",
    lastModified: "2024-03-19T09:45:00Z",
    author: "Legal Team",
  },
  {
    id: "8",
    name: { en: "FAQ Section", ar: "قسم الأسئلة الشائعة" },
    description: {
      en: "Frequently asked questions and answers.",
      ar: "الأسئلة الشائعة وإجاباتها.",
    },
    content: { en: "[faq-list count='10']", ar: "[faq-list count='10']" },
    template: "custom",
    breadcrumb_style: "center",
    breadcrumb_background: "",
    status: "archived",
    featured_image: "",
    faqs: [],
    seo: {
      meta_title: { en: "FAQ Section", ar: "الأسئلة الشائعة" },
      meta_description: {
        en: "Answers to the most common questions.",
        ar: "إجابات على أكثر الأسئلة شيوعًا.",
      },
      meta_image: "",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-03-10T13:20:00Z",
    lastModified: "2024-03-25T16:10:00Z",
    author: "Support Team",
  },
  {
    id: "9",
    name: { en: "Coming Soon", ar: "قريبًا" },
    description: { en: "Short description", ar: "وصف قصير" },
    content: {
      en: '[coming-soon title="Get Notified When We Launch" countdown_time="2026-02-24" address="58 Street Commercial Road Freston, Australia" business_hours="Mon - Sat: 8 am - 5 pm, Sunday: CLOSED" image="main/general/contact-ing.jpg"]',
      ar: '[coming-soon title="احصل على إشعار عند الإطلاق" countdown_time="2026-02-24" address="58 شارع الطريق التجاري فريستون، أستراليا" business_hours="الإثنين - السبت: 8 ص - 5 م، الأحد: مغلق" image="main/general/contact-ing.jpg"]',
    },
    template: "without-layout",
    breadcrumb_style: "start",
    breadcrumb_background: "",
    status: "published",
    featured_image: "",
    faqs: [],
    seo: {
      meta_title: { en: "Coming Soon", ar: "قريبًا" },
      meta_description: {
        en: "Get notified when we launch our new website.",
        ar: "احصل على إشعار عندما نطلق موقعنا الجديد.",
      },
      meta_image: "",
    },
    languages: ["en", "ar"],
    availableLanguages: [
      { code: "en", name: "English" },
      { code: "ar", name: "Arabic" },
      { code: "fr", name: "Francais" },
    ],
    createdAt: "2024-03-10T13:20:00Z",
    lastModified: "2024-03-25T16:10:00Z",
    author: "Admin User",
  },
];
