import { Feature, Plan } from "@/types";

// Dummy data for existing plans
export const dummyPlans: Plan[] = [
  {
    id: "PLN-001",
    key: "basic-plan",
    name: { en: "Basic Plan", ar: "الخطة الأساسية" },
    description: {
      en: "Perfect for small businesses and startups",
      ar: "مثالي للشركات الصغيرة والشركات الناشئة",
    },
    duration: "12",
    currency: "USD",
    price: "99",
    discountedPrice: "79",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: true,
    totalSubscriptions: 1500,
    customers: 1420,
    revenue: 45000,
    createdAt: "2024-01-15",
  },
  {
    id: "PLN-002",
    key: "pro-plan",
    name: { en: "Pro Plan", ar: "الخطة الاحترافية" },
    description: {
      en: "Advanced features for growing businesses",
      ar: "ميزات متقدمة للشركات النامية",
    },
    duration: "12",
    currency: "USD",
    price: "199",
    discountedPrice: "",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: true,
    totalSubscriptions: 850,
    customers: 800,
    revenue: 68000,
    createdAt: "2024-02-20",
  },
  {
    id: "PLN-003",
    key: "enterprise-plan",
    name: { en: "Enterprise Plan", ar: "الخطة المؤسسية" },
    description: {
      en: "Complete solution for large enterprises",
      ar: "حل كامل للشركات الكبيرة",
    },
    duration: "24",
    currency: "USD",
    price: "499",
    discountedPrice: "399",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: true,
    totalSubscriptions: 120,
    customers: 115,
    revenue: 115000,
    createdAt: "2024-01-10",
  },
  {
    id: "PLN-004",
    key: "starter-plan",
    name: { en: "Starter Plan", ar: "الخطة المبدئية" },
    description: {
      en: "Affordable plan to get started",
      ar: "خطة ميسورة للبدء",
    },
    duration: "6",
    currency: "USD",
    price: "49",
    discountedPrice: "",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: false,
    totalSubscriptions: 2300,
    customers: 2250,
    revenue: 34500,
    createdAt: "2024-03-05",
  },
  {
    id: "PLN-005",
    key: "premium-plan",
    name: { en: "Premium Plan", ar: "الخطة المميزة" },
    description: {
      en: "Best for agencies and professionals",
      ar: "الأفضل للوكالات والمحترفين",
    },
    duration: "12",
    currency: "USD",
    price: "299",
    discountedPrice: "249",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: true,
    totalSubscriptions: 420,
    customers: 400,
    revenue: 84000,
    createdAt: "2024-02-28",
  },
  {
    id: "PLN-006",
    key: "free-plan",
    name: { en: "Free Plan", ar: "الخطة المجانية" },
    description: {
      en: "Try our platform with limited features",
      ar: "جرّب منصتنا بميزات محدودة",
    },
    duration: "1",
    currency: "USD",
    price: "0",
    discountedPrice: "",
    vat: "0",
    vatDescription: {
      en: "No VAT applied",
      ar: "لا توجد ضريبة قيمة مضافة",
    },
    status: true,
    totalSubscriptions: 5800,
    customers: 5750,
    revenue: 0,
    createdAt: "2024-01-01",
  },
  {
    id: "PLN-007",
    key: "business-plan",
    name: { en: "Business Plan", ar: "خطة الأعمال" },
    description: {
      en: "Professional tools for mid-size teams",
      ar: "أدوات احترافية للفرق متوسطة الحجم",
    },
    duration: "12",
    currency: "USD",
    price: "399",
    discountedPrice: "349",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: false,
    totalSubscriptions: 320,
    customers: 300,
    revenue: 96000,
    createdAt: "2024-03-12",
  },
  {
    id: "PLN-008",
    key: "ultimate-plan",
    name: { en: "Ultimate Plan", ar: "الخطة النهائية" },
    description: {
      en: "All features unlocked with priority support",
      ar: "جميع الميزات متاحة مع دعم ذو أولوية",
    },
    duration: "24",
    currency: "USD",
    price: "699",
    discountedPrice: "599",
    vat: "15",
    vatDescription: {
      en: "Includes 15% VAT",
      ar: "يشمل 15% ضريبة القيمة المضافة",
    },
    status: true,
    totalSubscriptions: 95,
    customers: 90,
    revenue: 142500,
    createdAt: "2024-02-15",
  },
];

export const defaultFeatures: Feature[] = [
  {
    id: "1",
    name: { en: "Profile Views", ar: "مشاهدات الملف الشخصي" },
    tag: { en: "Infinity", ar: "لانهائي" },
    included: true,
    value: "Infinity",
  },
  {
    id: "2",
    name: { en: "Candidate Unlocks", ar: "فتح المرشحين" },
    tag: { en: "150", ar: "١٥٠" },
    included: true,
    value: "150",
  },
  {
    id: "3",
    name: { en: "Job Postings", ar: "نشر الوظائف" },
    tag: { en: "20", ar: "٢٠" },
    included: true,
    value: "20",
  },
  {
    id: "4",
    name: { en: "Invitations", ar: "الدعوات" },
    tag: { en: "60", ar: "٦٠" },
    included: true,
    value: "60",
  },
  {
    id: "5",
    name: { en: "Users", ar: "المستخدمين" },
    tag: { en: "3", ar: "٣" },
    included: true,
    value: "3",
  },
  {
    id: "6",
    name: { en: "Extra Access (months)", ar: "وصول إضافي (أشهر)" },
    tag: { en: "3", ar: "٣" },
    included: true,
    value: "3",
  },
  {
    id: "7",
    name: { en: "Priority Support", ar: "دعم مميز" },
    tag: { en: "Included", ar: "مضمن" },
    included: true,
  },
];
