import { Product } from "@/types/product";

// Dummy medical wear product data
export const products: Product[] = [
  {
    id: "1",
    brand: {
      id: 1,
      title: "MediPro",
      url: "/MediPro",
      image: "/images/MediPro.jpg",
    },
    model: "Scrub Set",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "MediPro Professional V-Neck Scrub Top & Pants Set",
    price: 4599,
    del_price: 5999,
    status: "Limited stock",
    rating: 4.7,
    sale: "23% OFF",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Orange", "White"],
    images: [
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1730710595034-Untitled-1.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1730710595035-Untitled-4.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1730713251887-Untitled-1.jpg&w=1920&q=70",
    ],
    isBestSaller: true,
    nudges: [
      "📌 Only 3 left in stock",
      "🔥 8 people viewing now",
      "⚡ Moisture-wicking fabric",
      "🚚 Delivery by tomorrow",
    ],
    reviewCount: 124,
    description: "Professional scrub set with antimicrobial treatment",
    features: [
      "V-neck top with side slits",
      "Straight leg pants with elastic waist",
      "Antimicrobial treatment",
      "Wrinkle-resistant fabric",
      "Multiple pockets for utility",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 1533,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "3 months installments at 0% interest", url: "#" },
      { title: "Free embroidery available", url: "#" },
    ],
    sellers: [
      {
        id: "seller1",
        name: "MediPro Official Store",
        rating: 4.8,
        positiveRatings: "94%",
        partnerSince: "2018",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "Professional-grade scrubs designed for healthcare workers with all-day comfort in mind. Made from durable, easy-care fabric that stands up to repeated washing.",
    highlights: [
      "Antimicrobial treatment reduces odor-causing bacteria",
      "Multiple pockets for convenient storage",
      "Wrinkle-resistant for professional appearance",
    ],
    specifications: [
      { label: "Material", content: "65% Polyester, 35% Cotton" },
      { label: "Color", content: "Navy, Royal Blue, Black" },
      { label: "Care Instructions", content: "Machine wash, tumble dry low" },
      { label: "Fit Type", content: "Regular Fit" },
      { label: "Closure Type", content: "Pull On" },
    ],
  },
  {
    id: "2",
    brand: {
      id: 2,
      title: "WhiteCoat",
      url: "/WhiteCoat",
      image: "/images/WhiteCoat.jpg",
    },
    model: "Lab Coat",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "WhiteCoat Professional Lab Coat with Embroidery Option",
    price: 6899,
    del_price: 8999,
    status: "New arrival",
    stock: 15,
    rating: 4.8,
    sale: "23% OFF",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Orange", "White"],
    images: [
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1725131056230-MM%20Photography-.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1725131056231-MM%20Photography-290.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1725131056230-MM%20Photography-.jpg&w=1920&q=70",
    ],
    isBestSaller: false,
    nudges: [
      "📌 Bestseller in Lab Coats",
      "🔥 Custom embroidery available",
      "⚡ Stain-resistant fabric",
      "🚚 Free returns",
    ],
    reviewCount: 87,
    description:
      "Professional lab coat with premium fabric and functional design",
    features: [
      "Premium cotton-polyester blend",
      "Notched lapel collar",
      "Three pockets (two lower, one chest)",
      "Side slits for ease of movement",
      "Optional embroidery service",
    ],
    deliveryDate: "2-3 days",
    installmentOptions: [
      {
        months: 3,
        amount: 2300,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "3 months installments at 0% interest", url: "#" },
      { title: "Free embroidery available", url: "#" },
    ],
    sellers: [
      {
        id: "seller2",
        name: "WhiteCoat Official Store",
        rating: 4.9,
        positiveRatings: "96%",
        partnerSince: "2017",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "A professional lab coat designed for doctors, nurses, and medical students. Features a classic design with modern functionality and premium fabric that resists stains and wrinkles.",
    highlights: [
      "Optional embroidery for personalization",
      "Stain-resistant fabric maintains professional appearance",
      "Functional pockets for daily use",
    ],
    specifications: [
      { label: "Material", content: "65% Polyester, 35% Cotton" },
      { label: "Color", content: "White" },
      { label: "Care Instructions", content: "Machine washable" },
      { label: "Fit Type", content: "Regular Fit" },
      { label: "Closure Type", content: "Button Front" },
    ],
  },
  {
    id: "3",
    brand: {
      id: 3,
      title: "NurseMates",
      url: "/NurseMates",
      image: "/images/NurseMates.jpg",
    },
    model: "Alicia",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "NurseMates Alicia Women's Medical Shoes",
    price: 7999,
    del_price: 9999,
    status: "Trending",
    rating: 4.6,
    sale: "20% OFF",
    sizes: ["38", "30", "40", "28"],
    colors: ["Black", "White", "Red"],
    images: [
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1720957542880-1.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1720957542880-1.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1720957542880-1.jpg&w=1920&q=70",
    ],
    isBestSaller: true,
    nudges: [
      "📌 Last few pairs left",
      "🔥 12 bought today",
      "⚡ Slip-resistant soles",
      "🚚 Includes arch support",
    ],
    reviewCount: 215,
    description:
      "Comfortable medical shoes designed for healthcare professionals",
    features: [
      "Slip-resistant rubber outsole",
      "Removable cushioned insole",
      "Lightweight design",
      "Breathable mesh upper",
      "Easy to clean",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 2666,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "3 months installments at 0% interest", url: "#" },
      { title: "Free shipping on all orders", url: "#" },
    ],
    sellers: [
      {
        id: "seller3",
        name: "NurseMates Official Store",
        rating: 4.7,
        positiveRatings: "92%",
        partnerSince: "2019",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "The NurseMates Alicia shoes are designed specifically for healthcare professionals who spend long hours on their feet. Features slip-resistant soles and cushioned support for all-day comfort.",
    highlights: [
      "Slip-resistant soles for safety",
      "Removable cushioned insole for comfort",
      "Easy to clean and maintain",
    ],
    specifications: [
      { label: "Material", content: "Mesh upper, rubber sole" },
      { label: "Color", content: "White, Black" },
      { label: "Shoe Width", content: "Medium" },
      { label: "Closure Type", content: "Lace-up" },
      { label: "Heel Height", content: "1 inch" },
    ],
  },
  {
    id: "4",
    brand: {
      id: 4,
      title: "SurgiCap",
      url: "/SurgiCap",
      image: "/images/SurgiCap.jpg",
    },
    model: "Bouffant",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "SurgiCap Disposable Bouffant Surgical Caps (100 Pack)",
    price: 2499,
    del_price: 3499,
    status: "Popular",
    rating: 4.5,
    sale: "29% OFF",
    images: [
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1720961738648-Untitled-1.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1720961738648-Untitled-2.jpg&w=1920&q=70",
      "https://www.drbrandscrubs.com/_next/image?url=https%3A%2F%2Fs.drbrandscrubs.com%2Fuploads%2F1730380870868-Untitled-2.jpg&w=1920&q=70",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Red"],
    isBestSaller: false,
    nudges: [
      "📌 Best for OR use",
      "🔥 100 caps per pack",
      "⚡ Latex-free material",
      "🚚 Free shipping",
    ],
    reviewCount: 342,
    description: "Disposable bouffant surgical caps for medical professionals",
    features: [
      "100 caps per package",
      "Latex-free and non-irritating",
      "Breathable material",
      "One-size-fits-all design",
      "Comfortable elastic band",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 833,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "Free shipping on all orders", url: "#" },
      { title: "Bulk discounts available", url: "#" },
    ],
    sellers: [
      {
        id: "seller4",
        name: "MedSupply Direct",
        rating: 4.6,
        positiveRatings: "91%",
        partnerSince: "2016",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "Disposable bouffant surgical caps designed for comfort and functionality in medical environments. Latex-free material is gentle on skin while providing secure coverage.",
    highlights: [
      "100 caps per package for value",
      "Latex-free material for sensitive skin",
      "Breathable fabric for comfort",
    ],
    specifications: [
      { label: "Material", content: "Non-woven polypropylene" },
      { label: "Color", content: "Blue" },
      { label: "Quantity", content: "100 caps" },
      { label: "Features", content: "Latex-free, breathable" },
      { label: "Size", content: "One size fits most" },
    ],
  },
  {
    id: "5",
    brand: {
      id: 5,
      title: "HealingHands",
      url: "/HealingHands",
      image: "/images/HealingHands.jpg",
    },
    model: "Compression Socks",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "HealingHands 15-20 mmHg Compression Socks (3 Pack)",
    price: 3899,
    del_price: 4999,
    status: "Hot deal",
    rating: 4.8,
    sale: "22% OFF",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Red"],
    images: [
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw182c65ac/images/large/1_hh-2285---sls_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw182c65ac/images/large/1_hh-2285---sls_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPGg",
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw15de2580/images/large/6_hh-2285---sls_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
    ],
    isBestSaller: true,
    nudges: [
      "📌 Doctor recommended",
      "🔥 30hr comfort guarantee",
      "⚡ 3-pack value",
      "🚚 Includes carrying case",
    ],
    reviewCount: 478,
    description: "Medical-grade compression socks for healthcare professionals",
    features: [
      "15-20 mmHg graduated compression",
      "Breathable moisture-wicking fabric",
      "Reinforced heel and toe",
      "Non-binding top band",
      "3-pack with assorted colors",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 1300,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "Free shipping on all orders", url: "#" },
      { title: "Subscribe & save 15%", url: "#" },
    ],
    sellers: [
      {
        id: "seller5",
        name: "HealingHands Medical",
        rating: 4.8,
        positiveRatings: "95%",
        partnerSince: "2015",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "Medical-grade compression socks designed specifically for healthcare professionals who spend long hours on their feet. Provides graduated compression to improve circulation and reduce fatigue.",
    highlights: [
      "15-20 mmHg medical-grade compression",
      "Moisture-wicking fabric keeps feet dry",
      "Reinforced heel and toe for durability",
    ],
    specifications: [
      { label: "Material", content: "85% Nylon, 15% Spandex" },
      { label: "Compression Level", content: "15-20 mmHg" },
      { label: "Quantity", content: "3 pairs" },
      {
        label: "Size",
        content: "S/M (shoe size 5-10), L/XL (shoe size 10-15)",
      },
      { label: "Features", content: "Graduated compression, moisture-wicking" },
    ],
  },
  {
    id: "6",
    brand: {
      id: 6,
      title: "ScrubLife",
      url: "/ScrubLife",
      image: "/images/ScrubLife.jpg",
    },
    model: "Jogger Scrubs",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "ScrubLife Men's Jogger Scrub Pants with Cargo Pockets",
    price: 4299,
    del_price: 5499,
    status: "Value pack",
    rating: 4.7,
    sale: "22% OFF",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Maroon", "Red"],
    images: [
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dwa73ac753/images/large/1_hh-hh701--pew_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw7dedf3e8/images/large/2_hh-hh701--pew_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw912ce286/images/large/4_hh-hh701--pew_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
    ],
    isBestSaller: false,
    nudges: [
      "📌 500+ bought today",
      "🔥 Modern jogger fit",
      "⚡ 7 functional pockets",
      "🚚 Free scrub top with purchase",
    ],
    reviewCount: 189,
    description: "Modern jogger-style scrub pants with multiple pockets",
    features: [
      "Jogger-style cuff at ankle",
      "7 functional pockets",
      "Elastic waist with drawstring",
      "Stretch fabric for mobility",
      "Wrinkle and stain resistant",
    ],
    deliveryDate: "24 May",
    installmentOptions: [
      {
        months: 3,
        amount: 1433,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "Free scrub top with purchase", url: "#" },
      { title: "3 months installments at 0% interest", url: "#" },
    ],
    sellers: [
      {
        id: "seller6",
        name: "ScrubLife Official Store",
        rating: 4.7,
        positiveRatings: "93%",
        partnerSince: "2018",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "Modern jogger-style scrub pants designed for healthcare professionals who want both style and functionality. Features multiple pockets and stretch fabric for all-day comfort.",
    highlights: [
      "Jogger-style cuff for modern look",
      "7 functional pockets for utility",
      "Stretch fabric allows full range of motion",
    ],
    specifications: [
      { label: "Material", content: "65% Polyester, 30% Cotton, 5% Spandex" },
      { label: "Color", content: "Navy, Charcoal, Forest Green" },
      { label: "Care Instructions", content: "Machine wash, tumble dry low" },
      { label: "Fit Type", content: "Jogger Fit" },
      { label: "Closure Type", content: "Elastic Waist with Drawstring" },
    ],
  },
  {
    id: "7",
    brand: {
      id: 7,
      title: "ORReady",
      url: "/ORReady",
      image: "/images/ORReady.jpg",
    },
    model: "Surgical Gown",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "ORReady Level 3 Disposable Surgical Gowns (25 Pack)",
    price: 8999,
    del_price: 11999,
    status: "Special offer",
    rating: 4.6,
    sale: "25% OFF",
    sizes: ["M", "L", "XL", "XXL"],
    images: [
      "https://shopcdnpro.grainajz.com/category/73695/1348/da3048e2afa28ec288c428d54142c0d7/71.jpg",
      "https://shopcdnpro.grainajz.com/category/73695/1348/6a8f3e99428a0f482f0aff80d352f847/00.jpg",
      "https://shopcdnpro.grainajz.com/category/73695/1348/328fc89dc719a8696ff15d1390715ed8/01.jpg",
    ],
    isBestSaller: true,
    nudges: [
      "📌 AAMI Level 3 protection",
      "🔥 25 gowns per box",
      "⚡ Fluid-resistant material",
      "🚚 2 year warranty",
    ],
    reviewCount: 156,
    description: "Level 3 disposable surgical gowns for medical professionals",
    features: [
      "AAMI Level 3 protection",
      "Reinforced critical zones",
      "Breathable material",
      "Thumb hooks for secure fit",
      "Latex-free",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 3000,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "Bulk discounts available", url: "#" },
      { title: "Free shipping on orders over ₹5000", url: "#" },
    ],
    sellers: [
      {
        id: "seller7",
        name: "MedEquip Supplies",
        rating: 4.7,
        positiveRatings: "94%",
        partnerSince: "2017",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "Level 3 disposable surgical gowns that provide critical zone protection against fluid penetration. Designed for surgical procedures where moderate to high fluid protection is needed.",
    highlights: [
      "AAMI Level 3 fluid protection",
      "Reinforced critical zones for safety",
      "Breathable material for comfort during long procedures",
    ],
    specifications: [
      { label: "Material", content: "SMS (Spunbond-Meltblown-Spunbond)" },
      { label: "Protection Level", content: "AAMI Level 3" },
      { label: "Quantity", content: "25 gowns per box" },
      { label: "Size", content: "Regular, Large, X-Large" },
      { label: "Features", content: "Fluid-resistant, breathable" },
    ],
  },
  {
    id: "8",
    brand: {
      id: 8,
      title: "StethoStyle",
      url: "/StethoStyle",
      image: "/images/StethoStyle.jpg",
    },
    model: "Warm-Up Jacket",
    category: {
      id: 1,
      title: "Medical Wear",
      url: "/medical-wear",
      image: "/images/medical-wear.jpg",
      subCategories: [
        { title: "Scrubs", url: "/medical-wear/scrubs" },
        { title: "Lab Coats", url: "/medical-wear/lab-coats" },
        { title: "Medical Shoes", url: "/medical-wear/shoes" },
        { title: "Surgical Caps", url: "/medical-wear/surgical-caps" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Scrubs",
          url: "/medical-wear/scrubs/best-selling",
        },
        { title: "New Arrivals", url: "/medical-wear/new-arrivals" },
      ],
    },
    title: "StethoStyle Fleece Warm-Up Jacket for Medical Professionals",
    price: 6599,
    del_price: 7999,
    status: "Almost gone",
    rating: 4.5,
    sale: "18% OFF",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Red"],
    images: [
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw07336ef5/images/large/1_hh-hh300f-roy_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPGhttps://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw07336ef5/images/large/1_hh-hh300f-roy_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw2cfb39aa/images/large/2_hh-hh300f-roy_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
      "https://www.healinghandsscrubs.com/dw/image/v2/BDTL_PRD/on/demandware.static/-/Sites-allheart-m-catalog/default/dw82c7ae22/images/large/4_hh-hh300f-roy_650.jpg?sw=650&sh=1000&sm=fit&sfrm=JPG",
    ],
    isBestSaller: false,
    nudges: [
      "📌 Last few sizes left",
      "🔥 Plush fleece lining",
      "⚡ Zippered pockets",
      "🚚 Ships today",
    ],
    reviewCount: 92,
    description: "Fleece warm-up jacket designed for medical professionals",
    features: [
      "Soft plush fleece lining",
      "Two zippered front pockets",
      "Rib-knit cuffs and waistband",
      "Embroidered logo option",
      "Machine washable",
    ],
    deliveryDate: "24 May",
    installmentOptions: [
      {
        months: 3,
        amount: 2200,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "3 months installments at 0% interest", url: "#" },
      { title: "Free embroidery available", url: "#" },
    ],
    sellers: [
      {
        id: "seller8",
        name: "StethoStyle Apparel",
        rating: 4.6,
        positiveRatings: "92%",
        partnerSince: "2019",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "A comfortable fleece warm-up jacket designed specifically for healthcare professionals. Perfect for wearing over scrubs in cold environments or during breaks.",
    highlights: [
      "Plush fleece lining for warmth",
      "Zippered pockets secure belongings",
      "Available with optional embroidery",
    ],
    specifications: [
      { label: "Material", content: "100% Polyester fleece" },
      { label: "Color", content: "Navy, Black, Royal Blue" },
      { label: "Care Instructions", content: "Machine wash, tumble dry low" },
      { label: "Fit Type", content: "Regular Fit" },
      { label: "Closure Type", content: "Full-zip" },
    ],
  },
  {
    id: "9",
    brand: {
      id: 9,
      title: "MediTech",
      url: "/MediTech",
      image: "/images/MediTech.jpg",
    },
    model: "VitalTrack Pro",
    category: {
      id: 2,
      title: "Medical Accessories",
      url: "/medical-accessories",
      image: "/images/medical-accessories.jpg",
      subCategories: [
        { title: "Watches", url: "/medical-accessories/watches" },
        { title: "Stethoscopes", url: "/medical-accessories/stethoscopes" },
        {
          title: "Diagnostic Tools",
          url: "/medical-accessories/diagnostic-tools",
        },
      ],
      featuredProducts: [
        {
          title: "Best Selling Watches",
          url: "/medical-accessories/watches/best-selling",
        },
        { title: "New Arrivals", url: "/medical-accessories/new-arrivals" },
      ],
    },
    title: "MediTech VitalTrack Pro Smartwatch for Healthcare Workers",
    price: 12999,
    del_price: 15999,
    status: "New arrival",
    rating: 4.7,
    sale: "19% OFF",
    images: [
      "https://f.nooncdn.com/p/pnsku/N70176351V/45/_/1747227180/ec2c3973-e042-433c-8e11-caadaf56cb91.jpg?width=800",
      "https://f.nooncdn.com/p/pnsku/N70176351V/45/_/1747227185/41476a14-3aaf-439d-826e-16f3350b4a05.jpg?width=800",
      "https://f.nooncdn.com/p/pnsku/N70176351V/45/_/1747227185/41476a14-3aaf-439d-826e-16f3350b4a05.jpg?width=800",
    ],
    isBestSaller: true,
    nudges: [
      "📌 Pulse ox & heart rate monitoring",
      "🔥 7-day battery life",
      "⚡ Hand wash timer",
      "🚚 Free screen protector",
    ],
    reviewCount: 215,
    description:
      "Medical-grade smartwatch with health monitoring features designed for healthcare professionals",
    features: [
      "Continuous heart rate monitoring",
      "Blood oxygen saturation tracking",
      "Hand hygiene timer with reminders",
      "7-day battery life",
      "Water resistant for clinical washing",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 6,
        amount: 2167,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "6 months installments at 0% interest", url: "#" },
      { title: "Free extended warranty", url: "#" },
    ],
    sellers: [
      {
        id: "seller9",
        name: "MediTech Official Store",
        rating: 4.8,
        positiveRatings: "95%",
        partnerSince: "2020",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "The VitalTrack Pro is designed specifically for medical professionals, featuring hospital-grade health monitoring and hygiene reminders to support clinical workflows.",
    highlights: [
      "FDA-cleared heart rate monitoring",
      "Automatic hand wash timer with compliance tracking",
      "Antimicrobial silicone band",
    ],
    specifications: [
      { label: "Display", content: '1.4" AMOLED Touchscreen' },
      { label: "Battery Life", content: "7 days typical use" },
      { label: "Water Resistance", content: "5 ATM (splash proof)" },
      { label: "Connectivity", content: "Bluetooth 5.0" },
      { label: "Compatibility", content: "iOS & Android" },
    ],
  },
  {
    id: "10",
    brand: {
      id: 10,
      title: "Clinique",
      url: "/Clinique",
      image: "/images/Clinique.jpg",
    },
    model: "SteriScent",
    category: {
      id: 3,
      title: "Medical Personal Care",
      url: "/medical-personal-care",
      image: "/images/medical-personal-care.jpg",
      subCategories: [
        { title: "Perfumes", url: "/medical-personal-care/perfumes" },
        { title: "Antimicrobial Soaps", url: "/medical-personal-care/soaps" },
        { title: "Hand Sanitizers", url: "/medical-personal-care/sanitizers" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Fragrances",
          url: "/medical-personal-care/perfumes/best-selling",
        },
        { title: "New Arrivals", url: "/medical-personal-care/new-arrivals" },
      ],
    },
    title:
      "Clinique SteriScent Antimicrobial Perfume for Healthcare Professionals",
    price: 3499,
    del_price: 4499,
    status: "Limited edition",
    rating: 4.6,
    sale: "22% OFF",
    sizes: ["50ml", "100ml"],
    images: [
      "https://f.nooncdn.com/p/v1633322266/N12890384A_1.jpg?width=800",
      "https://f.nooncdn.com/p/v1633322266/N12890384A_2.jpg?width=800",
      "https://f.nooncdn.com/p/v1633322266/N12890384A_3.jpg?width=800",
      "https://f.nooncdn.com/p/v1633322266/N12890384A_5.jpg?width=800",
      "https://f.nooncdn.com/p/v1633322266/N12890384A_6.jpg?width=800",
    ],
    isBestSaller: false,
    nudges: [
      "📌 Alcohol-free formula",
      "🔥 24-hour protection",
      "⚡ Won't interfere with sanitizers",
      "🚚 Ships today",
    ],
    reviewCount: 187,
    description:
      "Antimicrobial fragrance designed specifically for healthcare environments that won't interfere with sanitizers or patient care",
    features: [
      "Long-lasting subtle fragrance",
      "Antimicrobial properties",
      "Alcohol-free formula",
      "pH balanced for skin",
      "Compatible with frequent hand washing",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 1166,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "Free travel size with purchase", url: "#" },
      { title: "Subscribe & save 15%", url: "#" },
    ],
    sellers: [
      {
        id: "seller10",
        name: "Clinique Professional",
        rating: 4.7,
        positiveRatings: "93%",
        partnerSince: "2018",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "A first-of-its-kind antimicrobial fragrance designed specifically for healthcare professionals. Provides long-lasting subtle scent without interfering with clinical protocols.",
    highlights: [
      "Clinically tested antimicrobial properties",
      "Won't degrade effectiveness of hand sanitizers",
      "Specially formulated for healthcare environments",
    ],
    specifications: [
      { label: "Volume", content: "50ml, 100ml" },
      { label: "Fragrance Type", content: "Fresh, clean scent" },
      { label: "Active Ingredients", content: "Antimicrobial essential oils" },
      { label: "Alcohol Content", content: "0% (alcohol-free)" },
      { label: "Skin Type", content: "All skin types" },
    ],
  },
  {
    id: "11",
    brand: {
      id: 11,
      title: "DermaSeal",
      url: "/DermaSeal",
      image: "/images/DermaSeal.jpg",
    },
    model: "ProCare Kit",
    category: {
      id: 4,
      title: "Medical Supplies",
      url: "/medical-supplies",
      image: "/images/medical-supplies.jpg",
      subCategories: [
        {
          title: "Tapes & Dressings",
          url: "/medical-supplies/tapes-dressings",
        },
        { title: "Bandages", url: "/medical-supplies/bandages" },
        { title: "First Aid Kits", url: "/medical-supplies/first-aid" },
      ],
      featuredProducts: [
        {
          title: "Best Selling Dressings",
          url: "/medical-supplies/tapes-dressings/best-selling",
        },
        { title: "New Arrivals", url: "/medical-supplies/new-arrivals" },
      ],
    },
    title: "DermaSeal ProCare Medical Tape & Dressing Kit (100 Pieces)",
    price: 2499,
    del_price: 3299,
    status: "Bestseller",
    rating: 4.8,
    sale: "24% OFF",
    images: [
      "https://www.cokingmed.com/upload/1c/202109/porous-zinc-oxide-adhesive-tape.jpg",
      "https://www.cokingmed.com/upload/1c/202109/porous-zinc-oxide-adhesive-tape-2.jpg",
      "https://www.cokingmed.com/upload/1c/202109/porous-zinc-oxide-adhesive-tape-3.jpg",
    ],
    isBestSaller: true,
    nudges: [
      "📌 Hypoallergenic adhesive",
      "🔥 100-piece comprehensive kit",
      "⚡ Breathable fabric tape",
      "🚚 Free shipping",
    ],
    reviewCount: 342,
    description:
      "Complete medical tape and dressing kit for clinical and professional use",
    features: [
      "Hypoallergenic adhesive",
      "Breathable fabric tape",
      "Sterile dressings",
      "Water-resistant options",
      "Variety of sizes included",
    ],
    deliveryDate: "Tomorrow",
    installmentOptions: [
      {
        months: 3,
        amount: 833,
        methodType: {
          id: "1",
          name: "visa",
          price: 0,
          image: "/icons/card-visa.svg",
        },
      },
    ],
    bankOffers: [
      { title: "Free shipping on all orders", url: "#" },
      { title: "Bulk discounts available", url: "#" },
    ],
    sellers: [
      {
        id: "seller11",
        name: "Medical Supply Depot",
        rating: 4.9,
        positiveRatings: "97%",
        partnerSince: "2015",
        returnPolicy: "30 days return policy",
        itemShown: 90,
      },
    ],
    overview_desc:
      "Professional-grade medical tape and dressing kit containing 100 essential pieces for clinical use. Designed for durability and patient comfort with hypoallergenic materials.",
    highlights: [
      "Comprehensive 100-piece kit",
      "Hypoallergenic materials reduce skin irritation",
      "Includes both breathable and waterproof options",
    ],
    specifications: [
      {
        label: "Contents",
        content:
          "25 adhesive tapes, 50 sterile dressings, 25 specialty dressings",
      },
      { label: "Material", content: "Hypoallergenic fabric and adhesive" },
      { label: "Sterility", content: "Individually sterile packed dressings" },
      { label: "Water Resistance", content: "Some dressings water-resistant" },
      { label: "Latex Content", content: "Latex-free" },
    ],
  },
];
