import { ProductAttribute } from "@/types/product";

// Dummy data for product attributes
export const ProductAttributes: ProductAttribute[] = [
  {
    id: "1",
    name: { en: "Color", ar: "اللون" },
    slug: "color",
    sortOrder: 1,
    createdAt: "2024-01-15T10:30:00Z",
    status: { en: "published", ar: "نشط" },
    use_image_from_variation: true,
    display_layout: "visual_swatch",
    searchable: true,
    comparable: true,
    use_in_product_listing: true,
    categories: ["1", "3"],
    attributes: [
      {
        id: "1",
        title: { en: "Red", ar: "أحمر" },
        color: "#ff0000",
        image: null,
        is_default: true,
      },
      {
        id: "2",
        title: { en: "Blue", ar: "أزرق" },
        color: "#0000ff",
        image: null,
        is_default: false,
      },
      {
        id: "3",
        title: { en: "Green", ar: "أخضر" },
        color: "#00ff00",
        image: null,
        is_default: false,
      },
    ],
  },
  {
    id: "2",
    name: { en: "Size", ar: "المقاس" },
    slug: "size",
    sortOrder: 2,
    createdAt: "2024-01-16T14:20:00Z",
    status: { en: "published", ar: "نشط" },
    use_image_from_variation: false,
    display_layout: "dropdown",
    searchable: false,
    comparable: true,
    use_in_product_listing: false,
    categories: ["2", "4"],
    attributes: [
      {
        id: "1",
        title: { en: "Small", ar: "صغير" },
        color: "#cccccc",
        image: null,
        is_default: true,
      },
      {
        id: "2",
        title: { en: "Medium", ar: "متوسط" },
        color: "#cccccc",
        image: null,
        is_default: false,
      },
      {
        id: "3",
        title: { en: "Large", ar: "كبير" },
        color: "#cccccc",
        image: null,
        is_default: false,
      },
    ],
  },
  {
    id: "3",
    name: { en: "Material", ar: "المادة" },
    slug: "material",
    sortOrder: 3,
    createdAt: "2024-01-17T09:15:00Z",
    status: { en: "draft", ar: "مسودة" },
    use_image_from_variation: false,
    display_layout: "text_swatch",
    searchable: true,
    comparable: false,
    use_in_product_listing: true,
    categories: ["1", "2", "3"],
    attributes: [
      {
        id: "1",
        title: { en: "Cotton", ar: "قطن" },
        color: "#f5f5f5",
        image: null,
        is_default: true,
      },
      {
        id: "2",
        title: { en: "Polyester", ar: "بوليستر" },
        color: "#f5f5f5",
        image: null,
        is_default: false,
      },
    ],
  },
];
